apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-hub
  namespace: rhdh
  labels:
    app.kubernetes.io/name: developer-hub
    app.kubernetes.io/instance: rhdh
    app.kubernetes.io/part-of: developer-hub
