apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso
  namespace: rhsso
  labels:
    app: sso
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/managed-by: kustomize
spec:
  instances: 1
  externalAccess:
    enabled: true
    type: Route
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: JAVA_OPTS_APPEND
          value: "-Djboss.persistent.log.dir=/var/log/keycloak"
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
