apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: rhdh-client
  namespace: rhsso
  labels:
    app: sso
spec:
  client:
    redirectUris:
      # Correct redirect URI for OIDC authentication in RHDH
      - "https://backstage-developer-hub-rhdh.apps.cluster-ndb5l.ndb5l.sandbox500.opentlc.com/api/auth/oidc/handler/frame"
    webOrigins:
      - "https://backstage-developer-hub-rhdh.apps.cluster-ndb5l.ndb5l.sandbox500.opentlc.com"
      - "+"  # This allows redirect URIs to be valid web origins
